@startuml

' Primary Entity
class RailwayNetworkControl {
  +Control_ID: string <<PK>>
  Control_Name: string
  Power_Status: string
  Timestamp: number
  purge_id: string
}

' Secondary Entities
class TrackMonitoringSystem {
  +Monitor_ID: string <<PK>>
  Track_ID: string
  Condition_Status: string
  Timestamp: number
  purge_id: string
  Control_ID: string <<FK>>
}

class SwitchingMechanism {
  +Switch_ID: string <<PK>>
  Position: string
  Voltage_Input: number
  Timestamp: number
  purge_id: string
  Control_ID: string <<FK>>
}

class SignalControlUnit {
  +Signal_ID: string <<PK>>
  Signal_Type: string
  Status: string
  Timestamp: number
  purge_id: string
  Control_ID: string <<FK>>
}

class PowerDistributionUnit {
  +PowerDist_ID: string <<PK>>
  Voltage_Output: number
  Current_Output: number
  Timestamp: number
  purge_id: string
  Control_ID: string <<FK>>
}

' Tertiary Entities
class TrackStressSensor {
  +StressSensor_ID: string <<PK>>
  Stress_Level: number
  Timestamp: number
  purge_id: string
  Monitor_ID: string <<FK>>
}

class TrackWearSensor {
  +WearSensor_ID: string <<PK>>
  Wear_Level: number
  Timestamp: number
  purge_id: string
  Monitor_ID: string <<FK>>
}

class TrackObstructionSensor {
  +ObstructionSensor_ID: string <<PK>>
  Obstruction_Status: string
  Timestamp: number
  purge_id: string
  Monitor_ID: string <<FK>>
}

class TrackVibrationSensor {
  +VibrationSensor_ID: string <<PK>>
  Vibration_Level: number
  Timestamp: number
  purge_id: string
  Monitor_ID: string <<FK>>
}

class SwitchPositionSensor {
  +PositionSensor_ID: string <<PK>>
  Position: string
  Timestamp: number
  purge_id: string
  Switch_ID: string <<FK>>
}

class SwitchControlLever {
  +ControlLever_ID: string <<PK>>
  Position: string
  Timestamp: number
  purge_id: string
  Switch_ID: string <<FK>>
}

class SwitchPowerMonitor {
  +PowerMonitor_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  Switch_ID: string <<FK>>
}

class SwitchFeedbackSystem {
  +FeedbackSystem_ID: string <<PK>>
  Status: string
  Timestamp: number
  purge_id: string
  Switch_ID: string <<FK>>
}

class SignalLightController {
  +LightController_ID: string <<PK>>
  Light_Status: string
  Timestamp: number
  purge_id: string
  Signal_ID: string <<FK>>
}

class SignalTimer {
  +Timer_ID: string <<PK>>
  Time_Interval: string
  Timestamp: number
  purge_id: string
  Signal_ID: string <<FK>>
}

class SignalStatusMonitor {
  +StatusMonitor_ID: string <<PK>>
  Signal_Status: string
  Timestamp: number
  purge_id: string
  Signal_ID: string <<FK>>
}

class RemoteSignalTransmitter {
  +Transmitter_ID: string <<PK>>
  Signal_Type: string
  Signal_Strength: string
  Timestamp: number
  purge_id: string
  Signal_ID: string <<FK>>
}

class PowerLineMonitor {
  +LineMonitor_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  PowerDist_ID: string <<FK>>
}

class PowerRelay {
  +Relay_ID: string <<PK>>
  Voltage_Input: number
  Current_Output: number
  Timestamp: number
  purge_id: string
  PowerDist_ID: string <<FK>>
}

class PowerLoadBalancer {
  +LoadBalancer_ID: string <<PK>>
  Voltage_Level: number
  Current_Level: number
  Timestamp: number
  purge_id: string
  PowerDist_ID: string <<FK>>
}

class PowerConsumptionLogger {
  +Logger_ID: string <<PK>>
  Power_Consumption: number
  Timestamp: number
  purge_id: string
  PowerDist_ID: string <<FK>>
}

' Quaternary Entities
class TrackStressReading {
  +Reading_ID: string <<PK>>
  Stress_Level: number
  Timestamp: number
  purge_id: string
  StressSensor_ID: string <<FK>>
}

class StressCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  StressSensor_ID: string <<FK>>
}

class StressThresholdAlert {
  +Alert_ID: string <<PK>>
  Stress_Level: number
  Timestamp: number
  purge_id: string
  StressSensor_ID: string <<FK>>
}

class StressPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  StressSensor_ID: string <<FK>>
}

class WearReading {
  +Reading_ID: string <<PK>>
  Wear_Level: number
  Timestamp: number
  purge_id: string
  WearSensor_ID: string <<FK>>
}

class WearCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  WearSensor_ID: string <<FK>>
}

class WearThresholdAlert {
  +Alert_ID: string <<PK>>
  Wear_Level: number
  Timestamp: number
  purge_id: string
  WearSensor_ID: string <<FK>>
}

class WearPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  WearSensor_ID: string <<FK>>
}

class ObstructionReading {
  +Reading_ID: string <<PK>>
  Obstruction_Status: string
  Timestamp: number
  purge_id: string
  ObstructionSensor_ID: string <<FK>>
}

class ObstructionCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  ObstructionSensor_ID: string <<FK>>
}

class ObstructionAlert {
  +Alert_ID: string <<PK>>
  Obstruction_Status: string
  Timestamp: number
  purge_id: string
  ObstructionSensor_ID: string <<FK>>
}

class ObstructionPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  ObstructionSensor_ID: string <<FK>>
}

class VibrationReading {
  +Reading_ID: string <<PK>>
  Vibration_Level: number
  Timestamp: number
  purge_id: string
  VibrationSensor_ID: string <<FK>>
}

class VibrationCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  VibrationSensor_ID: string <<FK>>
}

class VibrationThresholdAlert {
  +Alert_ID: string <<PK>>
  Vibration_Level: number
  Timestamp: number
  purge_id: string
  VibrationSensor_ID: string <<FK>>
}

class VibrationPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  VibrationSensor_ID: string <<FK>>
}

class SwitchPositionReading {
  +Reading_ID: string <<PK>>
  Position: string
  Timestamp: number
  purge_id: string
  PositionSensor_ID: string <<FK>>
}

class PositionCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  PositionSensor_ID: string <<FK>>
}

class PositionAlert {
  +Alert_ID: string <<PK>>
  Position: string
  Timestamp: number
  purge_id: string
  PositionSensor_ID: string <<FK>>
}

class PositionPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  PositionSensor_ID: string <<FK>>
}

class ControlLeverReading {
  +LeverReading_ID: string <<PK>>
  Lever_Position: string
  Timestamp: number
  purge_id: string
  ControlLever_ID: string <<FK>>
}

class ControlLeverCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  ControlLever_ID: string <<FK>>
}

class ControlLeverAlert {
  +Alert_ID: string <<PK>>
  Lever_Position: string
  Timestamp: number
  purge_id: string
  ControlLever_ID: string <<FK>>
}

class ControlLeverPerformanceLog {
  +Log_ID: string <<PK>>
  Lever_Status: string
  Timestamp: number
  purge_id: string
  ControlLever_ID: string <<FK>>
}

class PowerMonitorReading {
  +PowerReading_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  PowerMonitor_ID: string <<FK>>
}

class PowerMonitorCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  PowerMonitor_ID: string <<FK>>
}

class PowerMonitorAlert {
  +Alert_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  PowerMonitor_ID: string <<FK>>
}

class PowerMonitorPerformanceLog {
  +Log_ID: string <<PK>>
  Sensor_Performance: string
  Timestamp: number
  purge_id: string
  PowerMonitor_ID: string <<FK>>
}

class FeedbackSystemLog {
  +FeedbackLog_ID: string <<PK>>
  Feedback_Status: string
  Timestamp: number
  purge_id: string
  FeedbackSystem_ID: string <<FK>>
}

class FeedbackCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  FeedbackSystem_ID: string <<FK>>
}

class FeedbackAlert {
  +Alert_ID: string <<PK>>
  Feedback_Status: string
  Timestamp: number
  purge_id: string
  FeedbackSystem_ID: string <<FK>>
}

class FeedbackPerformanceLog {
  +Log_ID: string <<PK>>
  Feedback_Performance: string
  Timestamp: number
  purge_id: string
  FeedbackSystem_ID: string <<FK>>
}

class SignalLightReading {
  +LightReading_ID: string <<PK>>
  Light_Status: string
  Timestamp: number
  purge_id: string
  LightController_ID: string <<FK>>
}

class SignalLightCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  LightController_ID: string <<FK>>
}

class SignalLightAlert {
  +Alert_ID: string <<PK>>
  Light_Status: string
  Timestamp: number
  purge_id: string
  LightController_ID: string <<FK>>
}

class SignalLightPerformanceLog {
  +Log_ID: string <<PK>>
  Light_Performance: string
  Timestamp: number
  purge_id: string
  LightController_ID: string <<FK>>
}

class SignalTimerLog {
  +TimerLog_ID: string <<PK>>
  Time_Interval: string
  Timestamp: number
  purge_id: string
  Timer_ID: string <<FK>>
}

class SignalTimerCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  Timer_ID: string <<FK>>
}

class SignalTimerAlert {
  +Alert_ID: string <<PK>>
  Time_Interval: string
  Timestamp: number
  purge_id: string
  Timer_ID: string <<FK>>
}

class SignalTimerPerformanceLog {
  +Log_ID: string <<PK>>
  Timer_Performance: string
  Timestamp: number
  purge_id: string
  Timer_ID: string <<FK>>
}

class SignalStatusLog {
  +StatusLog_ID: string <<PK>>
  Signal_Status: string
  Timestamp: number
  purge_id: string
  StatusMonitor_ID: string <<FK>>
}

class SignalStatusCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  StatusMonitor_ID: string <<FK>>
}

class SignalStatusAlert {
  +Alert_ID: string <<PK>>
  Signal_Status: string
  Timestamp: number
  purge_id: string
  StatusMonitor_ID: string <<FK>>
}

class SignalStatusPerformanceLog {
  +Log_ID: string <<PK>>
  Signal_Performance: string
  Timestamp: number
  purge_id: string
  StatusMonitor_ID: string <<FK>>
}

class TransmitterLog {
  +TransmitterLog_ID: string <<PK>>
  Signal_Strength: string
  Timestamp: number
  purge_id: string
  Transmitter_ID: string <<FK>>
}

class TransmitterCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: string
  Timestamp: number
  purge_id: string
  Transmitter_ID: string <<FK>>
}

class TransmitterAlert {
  +Alert_ID: string <<PK>>
  Signal_Strength: string
  Timestamp: number
  purge_id: string
  Transmitter_ID: string <<FK>>
}

class TransmitterPerformanceLog {
  +Log_ID: string <<PK>>
  Transmitter_Performance: string
  Timestamp: number
  purge_id: string
  Transmitter_ID: string <<FK>>
}

class LineMonitorReading {
  +MonitorReading_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  LineMonitor_ID: string <<FK>>
}

class LineMonitorCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  LineMonitor_ID: string <<FK>>
}

class LineMonitorAlert {
  +Alert_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  LineMonitor_ID: string <<FK>>
}

class LineMonitorPerformanceLog {
  +Log_ID: string <<PK>>
  Monitor_Performance: string
  Timestamp: number
  purge_id: string
  LineMonitor_ID: string <<FK>>
}

class RelayOperationLog {
  +RelayLog_ID: string <<PK>>
  Voltage_Input: number
  Current_Output: number
  Timestamp: number
  purge_id: string
  Relay_ID: string <<FK>>
}

class RelayCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  Relay_ID: string <<FK>>
}

class RelayAlert {
  +Alert_ID: string <<PK>>
  Relay_Status: string
  Timestamp: number
  purge_id: string
  Relay_ID: string <<FK>>
}

class RelayPerformanceLog {
  +Log_ID: string <<PK>>
  Relay_Performance: string
  Timestamp: number
  purge_id: string
  Relay_ID: string <<FK>>
}

class LoadBalancerLog {
  +LoadBalancerLog_ID: string <<PK>>
  Voltage_Level: number
  Current_Level: number
  Timestamp: number
  purge_id: string
  LoadBalancer_ID: string <<FK>>
}

class LoadBalancerCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  LoadBalancer_ID: string <<FK>>
}

class LoadBalancerAlert {
  +Alert_ID: string <<PK>>
  Voltage_Level: number
  Timestamp: number
  purge_id: string
  LoadBalancer_ID: string <<FK>>
}

class LoadBalancerPerformanceLog {
  +Log_ID: string <<PK>>
  LoadBalancer_Performance: string
  Timestamp: number
  purge_id: string
  LoadBalancer_ID: string <<FK>>
}

class PowerConsumptionLog {
  +ConsumptionLog_ID: string <<PK>>
  Power_Consumption: number
  Timestamp: number
  purge_id: string
  Logger_ID: string <<FK>>
}

class PowerConsumptionCalibrationData {
  +Calibration_ID: string <<PK>>
  Calibration_Value: number
  Timestamp: number
  purge_id: string
  Logger_ID: string <<FK>>
}

class PowerConsumptionAlert {
  +Alert_ID: string <<PK>>
  Power_Consumption: number
  Timestamp: number
  purge_id: string
  Logger_ID: string <<FK>>
}

class PowerConsumptionPerformanceLog {
  +Log_ID: string <<PK>>
  Consumption_Performance: string
  Timestamp: number
  purge_id: string
  Logger_ID: string <<FK>>
}

' Relationships
RailwayNetworkControl "1" -- "0..*" TrackMonitoringSystem
RailwayNetworkControl "1" -- "0..*" SwitchingMechanism
RailwayNetworkControl "1" -- "0..*" SignalControlUnit
RailwayNetworkControl "1" -- "0..*" PowerDistributionUnit

TrackMonitoringSystem "1" -- "0..*" TrackStressSensor
TrackMonitoringSystem "1" -- "0..*" TrackWearSensor
TrackMonitoringSystem "1" -- "0..*" TrackObstructionSensor
TrackMonitoringSystem "1" -- "0..*" TrackVibrationSensor

SwitchingMechanism "1" -- "0..*" SwitchPositionSensor
SwitchingMechanism "1" -- "0..*" SwitchControlLever
SwitchingMechanism "1" -- "0..*" SwitchPowerMonitor
SwitchingMechanism "1" -- "0..*" SwitchFeedbackSystem

SignalControlUnit "1" -- "0..*" SignalLightController
SignalControlUnit "1" -- "0..*" SignalTimer
SignalControlUnit "1" -- "0..*" SignalStatusMonitor
SignalControlUnit "1" -- "0..*" RemoteSignalTransmitter

PowerDistributionUnit "1" -- "0..*" PowerLineMonitor
PowerDistributionUnit "1" -- "0..*" PowerRelay
PowerDistributionUnit "1" -- "0..*" PowerLoadBalancer
PowerDistributionUnit "1" -- "0..*" PowerConsumptionLogger

TrackStressSensor "1" -- "0..*" TrackStressReading
TrackStressSensor "1" -- "0..*" StressCalibrationData
TrackStressSensor "1" -- "0..*" StressThresholdAlert
TrackStressSensor "1" -- "0..*" StressPerformanceLog

TrackWearSensor "1" -- "0..*" WearReading
TrackWearSensor "1" -- "0..*" WearCalibrationData
TrackWearSensor "1" -- "0..*" WearThresholdAlert
TrackWearSensor "1" -- "0..*" WearPerformanceLog

TrackObstructionSensor "1" -- "0..*" ObstructionReading
TrackObstructionSensor "1" -- "0..*" ObstructionCalibrationData
TrackObstructionSensor "1" -- "0..*" ObstructionAlert
TrackObstructionSensor "1" -- "0..*" ObstructionPerformanceLog

TrackVibrationSensor "1" -- "0..*" VibrationReading
TrackVibrationSensor "1" -- "0..*" VibrationCalibrationData
TrackVibrationSensor "1" -- "0..*" VibrationThresholdAlert
TrackVibrationSensor "1" -- "0..*" VibrationPerformanceLog

SwitchPositionSensor "1" -- "0..*" SwitchPositionReading
SwitchPositionSensor "1" -- "0..*" PositionCalibrationData
SwitchPositionSensor "1" -- "0..*" PositionAlert
SwitchPositionSensor "1" -- "0..*" PositionPerformanceLog

SwitchControlLever "1" -- "0..*" ControlLeverReading
SwitchControlLever "1" -- "0..*" ControlLeverCalibrationData
SwitchControlLever "1" -- "0..*" ControlLeverAlert
SwitchControlLever "1" -- "0..*" ControlLeverPerformanceLog

SwitchPowerMonitor "1" -- "0..*" PowerMonitorReading
SwitchPowerMonitor "1" -- "0..*" PowerMonitorCalibrationData
SwitchPowerMonitor "1" -- "0..*" PowerMonitorAlert
SwitchPowerMonitor "1" -- "0..*" PowerMonitorPerformanceLog

SwitchFeedbackSystem "1" -- "0..*" FeedbackSystemLog
SwitchFeedbackSystem "1" -- "0..*" FeedbackCalibrationData
SwitchFeedbackSystem "1" -- "0..*" FeedbackAlert
SwitchFeedbackSystem "1" -- "0..*" FeedbackPerformanceLog

SignalLightController "1" -- "0..*" SignalLightReading
SignalLightController "1" -- "0..*" SignalLightCalibrationData
SignalLightController "1" -- "0..*" SignalLightAlert
SignalLightController "1" -- "0..*" SignalLightPerformanceLog

SignalTimer "1" -- "0..*" SignalTimerLog
SignalTimer "1" -- "0..*" SignalTimerCalibrationData
SignalTimer "1" -- "0..*" SignalTimerAlert
SignalTimer "1" -- "0..*" SignalTimerPerformanceLog

SignalStatusMonitor "1" -- "0..*" SignalStatusLog
SignalStatusMonitor "1" -- "0..*" SignalStatusCalibrationData
SignalStatusMonitor "1" -- "0..*" SignalStatusAlert
SignalStatusMonitor "1" -- "0..*" SignalStatusPerformanceLog

RemoteSignalTransmitter "1" -- "0..*" TransmitterLog
RemoteSignalTransmitter "1" -- "0..*" TransmitterCalibrationData
RemoteSignalTransmitter "1" -- "0..*" TransmitterAlert
RemoteSignalTransmitter "1" -- "0..*" TransmitterPerformanceLog

PowerLineMonitor "1" -- "0..*" LineMonitorReading
PowerLineMonitor "1" -- "0..*" LineMonitorCalibrationData
PowerLineMonitor "1" -- "0..*" LineMonitorAlert
PowerLineMonitor "1" -- "0..*" LineMonitorPerformanceLog

PowerRelay "1" -- "0..*" RelayOperationLog
PowerRelay "1" -- "0..*" RelayCalibrationData
PowerRelay "1" -- "0..*" RelayAlert
PowerRelay "1" -- "0..*" RelayPerformanceLog

PowerLoadBalancer "1" -- "0..*" LoadBalancerLog
PowerLoadBalancer "1" -- "0..*" LoadBalancerCalibrationData
PowerLoadBalancer "1" -- "0..*" LoadBalancerAlert
PowerLoadBalancer "1" -- "0..*" LoadBalancerPerformanceLog

PowerConsumptionLogger "1" -- "0..*" PowerConsumptionLog
PowerConsumptionLogger "1" -- "0..*" PowerConsumptionCalibrationData
PowerConsumptionLogger "1" -- "0..*" PowerConsumptionAlert
PowerConsumptionLogger "1" -- "0..*" PowerConsumptionPerformanceLog

@enduml